const FETCH_PRODUCTS = 'FETCH_PRODUCTS'
const ON_LOADER = 'ON_LOADER'
const OFF_LOADER = 'OFF_LOADER'
const CATCH_ERROR = 'CATCH_ERROR'

export {
  FETCH_PRODUCTS,
  ON_LOADER,
  OFF_LOADER,
  CATCH_ERROR,
}
