const FETCH_PRODUCTS = 'FETCH_PRODUCTS'
const ON_LOADER = 'ON_LOADER'
const OFF_LOADER = 'OFF_LOADER'
const CATCH_ERROR = 'CATCH_ERROR'
const ADD_TO_BASKET = 'ADD_TO_BASKET'
const REMOVE_FROM_BASKET = 'REMOVE_FROM_BASKET'
const SAVE_BASKET = 'SAVE_BASKET'
const ON_SAVING = 'ON_SAVING'
const OFF_SAVING = 'OFF_SAVING'
const CLEAN_BASKET = 'CLEAN_BASKET'

export {
  FETCH_PRODUCTS,
  ON_LOADER,
  OFF_LOADER,
  CATCH_ERROR,
  ADD_TO_BASKET,
  REMOVE_FROM_BASKET,
  SAVE_BASKET,
  ON_SAVING,
  OFF_SAVING,
  CLEAN_BASKET
}
