const ADD_TO_BASKET = 'ADD_TO_BASKET'
const REMOVE_FROM_BASKET = 'REMOVE_FROM_BASKET'
const SAVE_BASKET = 'SAVE_BASKET'
const ON_SAVING = 'ON_SAVING'
const OFF_SAVING = 'OFF_SAVING'
const CLEAN_BASKET = 'CLEAN_BASKET'
const CATCH_ERROR = 'CATCH_ERROR'

export {
  ADD_TO_BASKET,
  REMOVE_FROM_BASKET,
  SAVE_BASKET,
  ON_SAVING,
  OFF_SAVING,
  CLEAN_BASKET,
  CATCH_ERROR
}
