const FETCHPRODUCTS = 'FETCH_PRODUCTS'
const CHANGELOADERSTATUS = 'CHANGE_LOADER_STATUS'
const CATCHERROR = 'CATCH_ERROR'
const INPUTCHANGE = 'INPUT_CHANGE'
const RESETINPUTS = 'RESET_INPUTS'

export {
  FETCHPRODUCTS,
  CHANGELOADERSTATUS,
  CATCHERROR,
  INPUTCHANGE,
  RESETINPUTS
}
